### PR TITLE
Change colour of text on tree

### PR DESCRIPTION
**Pull request by nixerus**
The black text (and brown text during new years) is really hard to read on such a dark background - especially for visually impaired users.

This makes the colours much lighter in hopes that it is easier to see.

### CODE REVIEW

**Review by cibikle — CHANGES_REQUESTED** [review]
Thanks for the PR! I was actually thinking just the other day, "gee, it's really hard to read the name of a selected node for some reason". Total oversight on my part.

But I think what the proposed change will actually do is turn all the node names white, which, on balance, will probably make it harder to read node names against the white background.

If you put an if on it so the text color is only set to white when it's the selected node, I think that'll address the problem.

**Comment by nixerus** [comment]
Ah, it appears this is an issue with the system appearance! For context, I'm using dark mode on Mac, and so this is what I see:

image

I'd imagine Eto handles this kind of thing as it wasn't an issue in v0.9.6 - removing the call to change the foreground color to black shows this:

image

I'll remove that line, and change the new years colour to "hot pink", as that's the only one off the top of my head I can think of that is visible enough on light and dark mode!

**Review by cibikle — COMMENTED** [review]
We'll certainly remove explicitly setting the text color outside of holidays—that caused problems for both darkmode and lightmode and didn't solve the problem it was meant to (which may not have existed in the first place).

The NY color works fine in lightmode, and I really don't want to change it from brown since that's kinda the whole point—the Christmas tree dies and turns brown on New Year's Day. I don't know if that's a common thing in the UK, but it's a well-known, time-honored phenomenon/joke in the US.

**However**, it clearly **must** be addressed with regard to darkmode, so we shall, but I'd rather do so as part of the user-editable color palette workitem (#48) to provide a more complete, targeted, and flexible solution, and I'd be grateful for any input or contributions you might have there.

**Comment by cibikle** [comment]
The default color issue has been addressed and will be reflected in the next release (expected sometime next week). Support for user-picked alternatives for holiday colors will be implemented by the time additional holidays are added or we get back to a New Year.

**Pull request closed without merging**
